### ISSUE TITLE
Add CDN into the src/index.html (Review Progress)

### ISSUE THREAD

**Issue by superoo7** [PhytoMark/bootstrap-starter#5]
Adding CDN to be default for faster loading and fallback if CDN is down, then use the local js/css/font

__Resources__
[CDN Fallback](https://www.hanselman.com/blog/CDNsFailButYourScriptsDontHaveToFallbackFromCDNToLocalJQuery.aspx)
[Bootstrap CDN link](http://getbootstrap.com/docs/4.0/getting-started/introduction/)

**Comment by MadhavBahl** [comment]
OK i will do it 👍
